# STDIO Example
# ------------------------------------------------------------------------------
# A simple STDIN / STDOUT example. This script is used in the getting started
# guide:
#
# https://docs.vector.dev/setup/getting-started/sending-your-first-event

[sources.in]
    type = "mqtt"
    address = "broker.hivemq.com"
    port = 1883
    topics = ["hello_1/mqtt", "hello_2/mqtt"]

[sinks.out]
  type = "file" # must be: "file"
  inputs = ["in"]
  path = "vector-%Y-%m-%d.log"
